import "./deploy";
import "./setLinker";
import "./setFeeToken";
import "./storeDeployments";
import "./mapContracts";
import "./unMapContracts";
import "./approveFees";
import "./setCrossChainGas";
import "./verify";
