/* eslint-disable prettier/prettier */
export const TASK_DEPLOY_STAKE = "DEPLOY_STAKE";
export const TASK_DEPLOY_VAULT = "DEPLOY_VAULT";
export const TASK_DEPLOY_ALL = "DEPLOY";
export const TASK_SET_LINKER = "SET_LINKER";
export const TASK_SET_FEES_TOKEN = "SET_FEES_TOKEN";
export const TASK_STORE_DEPLOYMENTS = "STORE_DEPLOYMENTS";
export const TASK_MAP_CONTRACT = "MAP_CONTRACTS";
export const TASK_UNMAP_CONTRACT = "UNMAP_CONTRACTS";
export const TASK_APPROVE_FEES = "APPROVE_FEES";
export const TASK_SET_STAKING_CONTRACT = "SET_STAKING_CONTRACT";
export const TASK_APPROVE_TOKENS = "APPROVE_TOKENS";
